### PR TITLE
Add comment field;

### PR DESCRIPTION
**Pull request by hming**

### CODE REVIEW

**Comment by Xethron** [comment]
Hello @hming. Thanks for this. I think we should just add a check to see if there is a comment, and only add the comment decorator if there is one...
(Man, took me 1 year to reply to this! Really sorry!)

**Comment by hming** [comment]
@Xethron Agree.

**Comment by Xethron** [comment]
No need to close it. We can continue working on it :)
Also, have a look at #52, it seems like a much more complex approach. Do both of these do the same thing?

**Comment by Xethron** [comment]
I actually realized it does check if the comment is set. Everything works great. Do you mind if I merge it in?

**Comment by Xethron** [comment]
Merged :) Thanks

**Pull request merged**
