### PR TITLE
Update MigrateGenerateCommand.php

### PR DESCRIPTION
**Pull request by ginzunza**
I added snake_case and camel_case to fix migration and class name error when tables has uppercase name.

### CODE REVIEW

**Comment by Xethron** [comment]
Wouldn't this also change the name of the table?

**Comment by ginzunza** [comment]
You are right!, I changes this line of code.

**Comment by Xethron** [comment]
Still not sure if I agree with changing the name of the table, even if it is only to lowercase. Personally, for me, the idea was not to assume a better database design with this project, but to replicate the database exactly.

If you feel strongly about this, I'd recommend making it an optional field you can pass in like `--lowercase-table-names` or something.

**Comment by Xethron** [comment]
This PR changes table names. Closing until its resolved

**Pull request closed without merging**
